<div class="content-selection-box">
	<p>Zamów pieczątkę online</p>
	<a class="sm-button-default slide-out-container"
       targeturl="<?php echo $this->url('order-begin')?>">Zamów</a>
</div>

<div class="content-selection-box">
	<p>Sprawdż status swojego zamówienia lub zmień dane</p>
	<a class="sm-button-default slide-out-container">Sprawdź</a>
</div>

<div class="content-selection-box">
	<p>Sprawdż status swojego zamówienia lub zmień dane</p>
	<a href="#" class="sm-button-default pull-right">Sprawdź</a>
</div>