<div class="content-selection-box">
	<p>Zamów pieczątkę online</p>
	<a class="sm-button-default slide-out-container">Zamów</a>
</div>

<div class="content-selection-box">
	<p>Sprawdż status swojego zamówienia lub zmień dane</p>
	<a class="sm-button-default">Sprawdź</a>
</div>

<div class="content-selection-box">
	<p>Sprawdż status swojego zamówienia lub zmień dane</p>
	<a href="#" class="sm-button-default pull-right">Sprawdź</a>
</div>