<div class="panel panel-primary">
	<div class="panel-heading"><?php echo $this->translate('Select stamp by type')?></div>
	<div class="panel-body">

	</div>
</div>

<div class="panel panel-primary">
	<div class="panel-heading"><?php echo $this->translate('Select stamp by manufacturer')?></div>
	<div class="panel-body">

	</div>
</div>

<div class="panel panel-primary">
	<div class="panel-heading"><?php echo $this->translate('Browse products')?></div>
	<div class="panel-body">

	</div>
</div>