<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Process\Module'                        => __DIR__ . '/Module.php',
    'Process\StorageProcess'                => __DIR__ . '/src/StorageProcess/StorageProcess.php',
    'Process\StampProcess'                  => __DIR__ . '/src/StorageProcess/StampProcess.php',
    'Process\RenderProcess'                 => __DIR__ . '/src/StorageProcess/RenderProcess.php',
    'Process\CommProcess'                   => __DIR__ . '/src/StorageProcess/CommProcess.php',
);
