<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Display\Module'                        => __DIR__ . '/Module.php',
    'Display\Controller\DisplayController' => __DIR__ . '/src/Display/Controller/DisplayController.php',
    'DisplayTest\Framework\TestCase'        => __DIR__ . '/tests/Display/Framework/TestCase.php',
    'DisplayTest\SampleTest'                => __DIR__ . '/tests/Display/SampleTest.php',
);
