--
-- Script was generated by Devart dbForge Studio for MySQL, Version 6.3.341.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2015-11-29 12:51:15
-- Server version: 5.6.17
-- Client version: 4.1
--


-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

-- 
-- Set default database
--
USE sm;

--
-- Definition for table sm_stamp_types
--
DROP TABLE IF EXISTS sm_stamp_types;
CREATE TABLE sm_stamp_types (
  id INT(11) NOT NULL AUTO_INCREMENT,
  stamp_name VARCHAR(70) BINARY NOT NULL,
  thumbnail VARCHAR(250) BINARY DEFAULT NULL,
  large_image VARCHAR(250) BINARY DEFAULT NULL,
  width FLOAT DEFAULT NULL,
  height FLOAT DEFAULT NULL,
  mass FLOAT DEFAULT NULL,
  manufacturer VARCHAR(70) BINARY DEFAULT NULL,
  date_created DATETIME DEFAULT NULL,
  date_modified DATETIME DEFAULT NULL,
  user_created INT(11) DEFAULT NULL,
  user_modified INT(11) DEFAULT NULL COMMENT 'Collection of stamp types',
  active TINYINT(4) DEFAULT 1,
  PRIMARY KEY (id),
  UNIQUE INDEX id_UNIQUE (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_bin;

--
-- Definition for table sm_users
--
DROP TABLE IF EXISTS sm_users;
CREATE TABLE sm_users (
  id INT(11) NOT NULL AUTO_INCREMENT,
  username VARCHAR(70) BINARY NOT NULL,
  email VARCHAR(250) BINARY NOT NULL,
  password VARCHAR(150) BINARY NOT NULL,
  date_registered DATETIME DEFAULT NULL,
  last_login DATETIME DEFAULT NULL,
  token VARCHAR(25) BINARY NOT NULL,
  avatar VARCHAR(250) BINARY DEFAULT NULL,
  country VARCHAR(45) BINARY DEFAULT NULL,
  city VARCHAR(60) BINARY DEFAULT NULL,
  province VARCHAR(60) BINARY DEFAULT NULL,
  zip VARCHAR(10) BINARY DEFAULT NULL,
  street VARCHAR(70) BINARY DEFAULT NULL,
  apartment VARCHAR(10) BINARY DEFAULT NULL,
  shipment INT(11) DEFAULT NULL,
  active TINYINT(4) DEFAULT 1 COMMENT 'Collection of users',
  first_name VARCHAR(50) BINARY DEFAULT NULL,
  last_name VARCHAR(80) BINARY DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX email_UNIQUE (email),
  UNIQUE INDEX id_UNIQUE (id),
  UNIQUE INDEX username_UNIQUE (username)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_bin;

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;