<div class="panel panel-primary">
    <div class="panel-heading"><?php echo $this->translate('Editing stamp type') ?></div>
    <div class="panel-body">
		<?php
			if ($error) { ?>
                <div class="alert alert-danger"><?php echo $this->translate('Stamp type not found.') ?></div>
                <a class="btn btn-default" href="<?php echo $this->url('admin-stamp-types') ?>">Back</a>
				<?php
			} else {
				?>
				<?php if (isset($updated) || $updated) { ?>
                    <div class="alert alert-success"><?php echo $this->translate('Record has been updated.') ?><br>
                        <a href="<?php echo $this->url('admin-stamp-types') ?>"><?php echo $this->translate('Back') ?></a>
                    </div>
					<?php
				} ?>
                <form method="POST">
                    <div class="input-group">
                        <span class="input-group-addon"
                              id="basic-addon3"><?php echo $this->translate('Stamp name') ?></span>
                        <input type="text" class="form-control" id="basic-url" aria-describedby="basic-addon3"
                               name="stamp_name" value="<?php echo $stamp['stamp_name'] ?>">
                    </div>

                    <br>

                    <div class="input-group">
                        <span class="input-group-addon"
                              id="basic-addon3"><?php echo $this->translate('Description') ?></span>
                        <textarea name="description" class="form-control"
                                  style="height:200px"><?php echo $stamp['description'] ?></textarea>
                    </div>

                    <br>

                    <div class="input-group">
                        <span class="input-group-addon"
                              id="basic-addon3"><?php echo $this->translate('Manufacturer') ?></span>
                        <input type="text" class="form-control" id="basic-url" aria-describedby="basic-addon3"
                               name="manufacturer" value="<?php echo $stamp['manufacturer'] ?>">
                    </div>

                    <br>

                    <div class="input-group" style="width: 200px; float:left;">
                        <span class="input-group-addon" id="basic-addon3"><?php echo $this->translate('Mass') ?></span>
                        <input type="text" class="form-control" id="basic-url" aria-describedby="basic-addon3"
                               name="mass" value="<?php echo $stamp['mass'] ?>">
                    </div>

                    <div class="input-group" style="width: 200px; float:left;">
                        <span class="input-group-addon" id="basic-addon3"><?php echo $this->translate('Width') ?></span>
                        <input type="text" class="form-control" id="basic-url" aria-describedby="basic-addon3"
                               name="width" value="<?php echo $stamp['width'] ?>">
                    </div>

                    <div class="input-group" style="width: 200px; float:left;">
                        <span class="input-group-addon"
                              id="basic-addon3"><?php echo $this->translate('Height') ?></span>
                        <input type="text" class="form-control" id="basic-url" aria-describedby="basic-addon3"
                               name="height" value="<?php echo $stamp['height'] ?>">
                    </div>

                    <div class="input-group">
                          <span class="input-group-addon">
                            <input type="checkbox" aria-label="Active" name="active" value="1" <?php if ($stamp['active']) echo "checked"?>>
                          </span>
                        <input type="text" class="form-control" value="<?php echo $this->translate('Active')?>" readonly>
                    </div>
                    <br><br>

                    <img class="admin-stamp-thumbnail" src="<?php echo $this->basePath('/') . \SmConfig::getImagePublicPath() . $stamp['thumbnail']?>">
                    <input type="file" name="thumbnail">

                    <img class="admin-stamp-large-image" src="<?php echo $this->basePath('/') . \SmConfig::getImagePublicPath() . $stamp['large_image']?>">
                    <input type="file" name="image">
                    <input type="submit" value="<?php echo $this->translate('Save') ?>" class="btn btn-success pull-right">
                </form>
			<?php } ?>
    </div>
</div>
<?php

var_dump($stamp);