<?php foreach ($stamps as $stamp) {?>

<div class="stamp-type-box">
    <a href="<?php echo $this->url('edit-stamp-type') . '?id=' . $stamp['id']?>">
    <img src="<?php echo $this->basePath('/') . \SmConfig::getImagePublicPath() . $stamp['thumbnail']?>">
    </a>
    <h4 class="manufacturer"><?php echo $stamp['manufacturer']?></h4>
    <h4 class="name"><?php echo $stamp['stamp_name']?></h4>
</div>
<?php } ?>
