<?php echo $this->doctype(); ?>

<?php $loggedIn = $this->loggedIn; ?>

<html lang="en">
<head>
<meta charset="utf-8">
        <?php echo $this->headTitle($this->configuration['page-title']['c_value'])?>

        <?php
        
        echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')?>
        <?php
        echo $this->headLink(array(
            'rel' => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $this->basePath() . '/img/favicon.ico'
        ))
            ->prependStylesheet($this->basePath() . '/css/style.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')?>
        <?php
        echo $this->headScript()
            ->prependFile($this->basePath() . '/js/scripts.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array(
            'conditional' => 'lt IE 9'
        ))
            ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array(
            'conditional' => 'lt IE 9'
        ));
        ?>
</head>
<body>

<!-- Navigation -->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php echo $this->url('application') ?>">Stamp Master</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
                <li><a href="#">Link</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">Separated link</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">One more separated link</a></li>
                    </ul>
                </li>
            </ul>
            <form class="navbar-form navbar-left" role="search">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search">
                </div>
                <button type="submit" class="btn btn-default">Submit</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">Link</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                       aria-haspopup="true" aria-expanded="false">
                        <?php if ($loggedIn) {
                            echo $userData['username'];
                        } else {
                            echo $this->translate("Account");
                        }
                        ?> <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <?php if ($loggedIn) { ?>
                            <li><a href="#">My account</a></li>
                            
                            <li><a href="<?php echo $this->url('admin-dashboard') ?>">
                                    <?php echo $this->translate('Administration') ?>
                                </a></li>
                            <li role="separator" class="divider"></li>
                            <li><a
                                   href="<?php echo $this->url('logout-user')?>">
                                    <?php echo $this->translate('Logout')?>
                                </a>
                            </li>
                        <?php } else { ?>
                            <li>
                                <a  href="<?php echo $this->url('login-user')?>">
                                    <?php echo $this->translate('Login')?>
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url('register-user')?>">
                                    <?php echo $this->translate('Register')?>
                                </a>
                            </li>
                        <?php } ?>
                    </ul>
                </li>
                <li>&nbsp;&nbsp;&nbsp;</li>
            </ul>

        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
<!-- EO Navigation -->
	<div class="container">
            <?php echo $this->content; ?>
        </div>
	<div class="div-footer">
		<footer>
			<p>&copy; 2012 - <?php echo date('Y') ?> by Archangel Design. All rights reserved</p>
		</footer>
	</div>
    <div id="global-overlay"></div>
        <?php echo $this->inlineScript()?>
    </body>
</html>
