<?php echo $this->partial('admin/admin/menu.phtml') ?>

<div class="panel panel-primary">
    <div class="panel-heading"><?php echo $this->translate('Configuration')?></div>
    <div class="panel-body">
        <table class="config-table">
            <tr>
                <td>ID</td><td><?php echo $this->translate('Parameter name')?></td>
                <td><?php echo $this->translate('Parameter value')?></td>
                <td></td>
            </tr>
            <?php foreach ($this->entireConfig as $config):?>
                <tr>
                    <td><?php echo $config['id']?></td>
                    <td><?php echo $config['c_name']?></td>
                    <?php if ($config['extended'] == 0){ ?>
                        <td><?php echo $config['c_value']?></td>
                    <?php } else { ?>
                        <td><?php echo $config['e_value']?></td>
                    <?php } ?>
                    <td>
                        <button class="btn btn-default" onclick="changeConfigValue(<?php echo $config['id']?>)">
                            <?php echo $this->translate('Change')?>
                        </button>
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>
</div>

<?php
var_dump($this->entireConfig)
?>


<script>
    function changeConfigValue(id)
    {
        $(".config-value-window").fadeIn();
        $("#global-overlay").fadeIn();
        $(".config-value-window").load('<?php echo $this->url('config-set-value')?>?id='+id);
    }
</script>

<div class="config-value-window modal-box">

</div>